In [4]:
import pandas as pd
df=pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [10]:
from sklearn.preprocessing import OrdinalEncoder

orders=[['Iris-virginica','Iris-setosa','Iris-versicolor']]

ohe= OrdinalEncoder(categories=orders)
ohe

OrdinalEncoder(categories=[['Iris-virginica', 'Iris-setosa',
                            'Iris-versicolor']])

In [7]:
df.Species.value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [11]:
ohe.fit_transform(df[['Species']])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [23]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [36]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
data=enc.fit_transform(df[['Species']]).toarray()
data

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [41]:
encoded_df = pd.DataFrame(data, columns=ohe.get_feature_names_out(['Species']), index=df.index)
encoded_df

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                    1.0                      0.0                     0.0
1                    1.0                      0.0                     0.0
2                    1.0                      0.0                     0.0
3                    1.0                      0.0                     0.0
4                    1.0                      0.0                     0.0
..                   ...                      ...                     ...
145                  0.0                      0.0                     1.0
146                  0.0                      0.0                     1.0
147                  0.0                      0.0                     1.0
148                  0.0                      0.0                     1.0
149                  0.0                      0.0                     1.0

[150 rows x 3 columns]

In [44]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [47]:
final_df = pd.concat([df.drop(columns=['Species']), encoded_df], axis=1)
final_df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,2,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,3,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5,5.0,3.6,1.4,0.2,1.0,0.0,0.0

In [48]:
final_df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species_Iris-setosa', 'Species_Iris-versicolor',
       'Species_Iris-virginica'],
      dtype='str')

In [50]:

final_df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,2,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,3,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5,5.0,3.6,1.4,0.2,1.0,0.0,0.0

In [ ]:
final_df['SepalLengthCm'].apply(lamdba x:x*20)

In [63]:

final_df['new_ohe'] = (
    final_df['Species_Iris-setosa'].astype(str) + "," +
    final_df['Species_Iris-versicolor'].astype(str) + "," +
    final_df['Species_Iris-virginica'].astype(str)
)
final_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica,new_ohe
0,1,5.1,3.5,1.4,0.2,1.0,0.0,0.0,"1.0,0.0,0.0"
1,2,4.9,3.0,1.4,0.2,1.0,0.0,0.0,"1.0,0.0,0.0"
2,3,4.7,3.2,1.3,0.2,1.0,0.0,0.0,"1.0,0.0,0.0"
3,4,4.6,3.1,1.5,0.2,1.0,0.0,0.0,"1.0,0.0,0.0"
4,5,5.0,3.6,1.4,0.2,1.0,0.0,0.0,"1.0,0.0,0.0"
...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,0.0,0.0,1.0,"0.0,0.0,1.0"
146,147,6.3,2.5,5.0,1.9,0.0,0.0,1.0,"0.0,0.0,1.0"
147,148,6.5,3.0,5.2,2.0,0.0,0.0,1.0,"0.0,0.0,1.0"
148,149,6.2,3.4,5.4,2.3,0.0,0.0,1.0,"0.0,0.0,1.0"
149,150,5.9,3.0,5.1,1.8,0.0,0.0,1.0,"0.0,0.0,1.0"

In [64]:
final_df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species_Iris-setosa', 'Species_Iris-versicolor',
       'Species_Iris-virginica', 'new_ohe'],
      dtype='str')

In [73]:
final_df.drop(columns=['Id','Species_Iris-setosa','Species_Iris-versicolor','Species_Iris-virginica'])

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      new_ohe
0              5.1           3.5            1.4           0.2  1.0,0.0,0.0
1              4.9           3.0            1.4           0.2  1.0,0.0,0.0
2              4.7           3.2            1.3           0.2  1.0,0.0,0.0
3              4.6           3.1            1.5           0.2  1.0,0.0,0.0
4              5.0           3.6            1.4           0.2  1.0,0.0,0.0
..             ...           ...            ...           ...          ...
145            6.7           3.0            5.2           2.3  0.0,0.0,1.0
146            6.3           2.5            5.0           1.9  0.0,0.0,1.0
147            6.5           3.0            5.2           2.0  0.0,0.0,1.0
148            6.2           3.4            5.4           2.3  0.0,0.0,1.0
149            5.9           3.0            5.1           1.8  0.0,0.0,1.0

[150 rows x 5 columns]

In [58]:
final_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica,new_ohe
0,1,5.1,3.5,1.4,0.2,1.0,0.0,0.0,NaN
1,2,4.9,3.0,1.4,0.2,1.0,0.0,0.0,NaN
2,3,4.7,3.2,1.3,0.2,1.0,0.0,0.0,NaN
3,4,4.6,3.1,1.5,0.2,1.0,0.0,0.0,NaN
4,5,5.0,3.6,1.4,0.2,1.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,0.0,0.0,1.0,NaN
146,147,6.3,2.5,5.0,1.9,0.0,0.0,1.0,NaN
147,148,6.5,3.0,5.2,2.0,0.0,0.0,1.0,NaN
148,149,6.2,3.4,5.4,2.3,0.0,0.0,1.0,NaN
149,150,5.9,3.0,5.1,1.8,0.0,0.0,1.0,NaN

In [ ]:
# built-in

print('hello')

# user-defined function


def add(var1,var2):
    return var1+var2

add(10,30)

# short hand writing 
var1=lamdba x+y
var1(3,4)

In [53]:
var1=lambda x,y:x+y
var1(3,4)

7

In [60]:
var1=10
str(var1)

'10'

In [74]:
# indexing of data frame


df=pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [75]:
len(df)

150

In [78]:
# slicing method / by location - iloc / by label - loc


df.loc[:,:]  # row, columns

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [81]:
df.iloc[:10,df.columns=='Species']

       Species
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa
5  Iris-setosa
6  Iris-setosa
7  Iris-setosa
8  Iris-setosa
9  Iris-setosa

In [82]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [83]:
df=df.drop(columns=['Id'])
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [84]:
df.loc[:,df.columns!='Species']

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [85]:
X=df.loc[:,df.columns!='Species']
y=df['Species']

In [86]:
X.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [87]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: str

In [91]:
df.iloc[10:50:2,1:3]  #row_indexer, column_indexer

    SepalWidthCm  PetalLengthCm
10           3.7            1.5
12           3.0            1.4
14           4.0            1.2
16           3.9            1.3
18           3.8            1.7
20           3.4            1.7
22           3.6            1.0
24           3.4            1.9
26           3.4            1.6
28           3.4            1.4
30           3.1            1.6
32           4.1            1.5
34           3.1            1.5
36           3.5            1.3
38           3.0            1.3
40           3.5            1.3
42           3.2            1.3
44           3.8            1.9
46           3.8            1.6
48           3.7            1.5

In [93]:
df.loc[df['SepalWidthCm']>3.5,:]

# PetalLenth > 1.5 , PetalWidthCm	Species

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
4              5.0           3.6            1.4           0.2     Iris-setosa
5              5.4           3.9            1.7           0.4     Iris-setosa
10             5.4           3.7            1.5           0.2     Iris-setosa
14             5.8           4.0            1.2           0.2     Iris-setosa
15             5.7           4.4            1.5           0.4     Iris-setosa
16             5.4           3.9            1.3           0.4     Iris-setosa
18             5.7           3.8            1.7           0.3     Iris-setosa
19             5.1           3.8            1.5           0.3     Iris-setosa
21             5.1           3.7            1.5           0.4     Iris-setosa
22             4.6           3.6            1.0           0.2     Iris-setosa
32             5.2           4.1            1.5           0.1     Iris-setosa
33             5.5           4.2            1.4           0.2     Iris-setosa
44             5.1           3.8            1.9           0.4     Iris-setosa
46             5.1           3.8            1.6           0.2     Iris-setosa
48             5.3           3.7            1.5           0.2     Iris-setosa
109            7.2           3.6            6.1           2.5  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
131            7.9           3.8            6.4           2.0  Iris-virginica

In [94]:
df.loc[df["PetalLengthCm"] > 1.5, ["PetalWidthCm", "Species"]]

     PetalWidthCm         Species
5             0.4     Iris-setosa
11            0.2     Iris-setosa
18            0.3     Iris-setosa
20            0.2     Iris-setosa
23            0.5     Iris-setosa
..            ...             ...
145           2.3  Iris-virginica
146           1.9  Iris-virginica
147           2.0  Iris-virginica
148           2.3  Iris-virginica
149           1.8  Iris-virginica

[113 rows x 2 columns]