In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder 

df=pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
# LabelEnconder , OrdinalEncoder, Customized encoder, One-hot encoder
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder 

lbl=LabelEncoder()
onehot=OneHotEncoder()
ordinalend=OrdinalEncoder()

In [6]:
df['lbl_encoder']=lbl.fit_transform(df[["Species"]])
df.head()

d:\globalenv\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,lbl_encoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0

In [7]:
df['or_encoder']=ordinalend.fit_transform(df[["Species"]])
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,lbl_encoder,or_encoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0,0.0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0,0.0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0,0.0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0,0.0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0,0.0

In [11]:
df['onehot_encoder']=list(onehot.fit_transform(df[["Species"]]).toarray())
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,lbl_encoder,or_encoder,onehot_encoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]"
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]"
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]"
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]"
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]"

In [12]:
df.Species.unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [13]:
pairs={
    'Iris-setosa':1.2,
    'Iris-versicolor':2.3,
    'Iris-virginica':3.5
}
pairs

{'Iris-setosa': 1.2, 'Iris-versicolor': 2.3, 'Iris-virginica': 3.5}

In [15]:
df['custom_encoder']=df['Species'].map(pairs)
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,lbl_encoder,or_encoder,onehot_encoder,custom_encoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2

In [16]:
df.dtypes

Id                  int64
SepalLengthCm     float64
SepalWidthCm      float64
PetalLengthCm     float64
PetalWidthCm      float64
Species               str
lbl_encoder         int64
or_encoder        float64
onehot_encoder     object
custom_encoder    float64
dtype: object

In [17]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,lbl_encoder,or_encoder,onehot_encoder,custom_encoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0,0.0,"[1.0, 0.0, 0.0]",1.2
...,...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,2,2.0,"[0.0, 0.0, 1.0]",3.5
146,147,6.3,2.5,5.0,1.9,Iris-virginica,2,2.0,"[0.0, 0.0, 1.0]",3.5
147,148,6.5,3.0,5.2,2.0,Iris-virginica,2,2.0,"[0.0, 0.0, 1.0]",3.5
148,149,6.2,3.4,5.4,2.3,Iris-virginica,2,2.0,"[0.0, 0.0, 1.0]",3.5
149,150,5.9,3.0,5.1,1.8,Iris-virginica,2,2.0,"[0.0, 0.0, 1.0]",3.5

In [19]:
# missing values
df.isnull().sum()

Id                0
SepalLengthCm     0
SepalWidthCm      0
PetalLengthCm     0
PetalWidthCm      0
Species           0
lbl_encoder       0
or_encoder        0
onehot_encoder    0
custom_encoder    0
dtype: int64

In [20]:
ames=pd.read_csv('data/AmesHousing.csv')
ames.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [21]:
ames.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   str
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   str
 7   Alley            198 non-null    str
 8   Lot Shape        2930 non-null   str
 9   Land Contour     2930 non-null   str
 10  Utilities        2930 non-null   str
 11  Lot Config       2930 non-null   str
 12  Land Slope       2930 non-null   str
 13  Neighborhood     2930 non-null   str
 14  Condition 1      2930 non-null   str
 15  Condition 2      2930 non-null   str
 16  Bldg Type        2930 non-null   str
 17  House Style      2930 non-null   str
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   str
 23  Roof Matl        2930 non-null   str
 24  Exterior 1st     2930 non-null   str
 25  Exterior 2nd     2930 non-null   str
 26  Mas Vnr Type     1155 non-null   str
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   str
 29  Exter Cond       2930 non-null   str
 30  Foundation       2930 non-null   str
 31  Bsmt Qual        2850 non-null   str
 32  Bsmt Cond        2850 non-null   str
 33  Bsmt Exposure    2847 non-null   str
 34  BsmtFin Type 1   2850 non-null   str
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   str
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   str
 41  Heating QC       2930 non-null   str
 42  Central Air      2930 non-null   str
 43  Electrical       2929 non-null   str
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   str
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   str
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   str
 59  Garage Type      2773 non-null   str
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   str
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   str
 65  Garage Cond      2771 non-null   str
 66  Paved Drive      2930 non-null   str
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     str
 74  Fence            572 non-null    str
 75  Misc Feature     106 non-null    str
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   str
 80  Sale Condition   2930 non-null   str
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), str(43)
memory usage: 1.8 MB

In [22]:
ames.isnull().sum()

Order               0
PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      490
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 82, dtype: int64

In [24]:
ames.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='str')

In [28]:
ames.select_dtypes(include='int').columns

Index(['Order', 'PID', 'MS SubClass', 'Lot Area', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd',
       'Fireplaces', 'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch',
       '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold',
       'Yr Sold', 'SalePrice'],
      dtype='str')

In [29]:
ames.select_dtypes(include='int').isnull().sum()

Order              0
PID                0
MS SubClass        0
Lot Area           0
Overall Qual       0
Overall Cond       0
Year Built         0
Year Remod/Add     0
1st Flr SF         0
2nd Flr SF         0
Low Qual Fin SF    0
Gr Liv Area        0
Full Bath          0
Half Bath          0
Bedroom AbvGr      0
Kitchen AbvGr      0
TotRms AbvGrd      0
Fireplaces         0
Wood Deck SF       0
Open Porch SF      0
Enclosed Porch     0
3Ssn Porch         0
Screen Porch       0
Pool Area          0
Misc Val           0
Mo Sold            0
Yr Sold            0
SalePrice          0
dtype: int64

In [30]:
ames.select_dtypes(include='float').isnull().sum()

Lot Frontage      490
Mas Vnr Area       23
BsmtFin SF 1        1
BsmtFin SF 2        1
Bsmt Unf SF         1
Total Bsmt SF       1
Bsmt Full Bath      2
Bsmt Half Bath      2
Garage Yr Blt     159
Garage Cars         1
Garage Area         1
dtype: int64

In [31]:
ames.select_dtypes(include='str').isnull().sum()

C:\Users\USER\AppData\Local\Temp\ipykernel_11884\3212452788.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  ames.select_dtypes(include='object').isnull().sum()

MS Zoning            0
Street               0
Alley             2732
Lot Shape            0
Land Contour         0
Utilities            0
Lot Config           0
Land Slope           0
Neighborhood         0
Condition 1          0
Condition 2          0
Bldg Type            0
House Style          0
Roof Style           0
Roof Matl            0
Exterior 1st         0
Exterior 2nd         0
Mas Vnr Type      1775
Exter Qual           0
Exter Cond           0
Foundation           0
Bsmt Qual           80
Bsmt Cond           80
Bsmt Exposure       83
BsmtFin Type 1      80
BsmtFin Type 2      81
Heating              0
Heating QC           0
Central Air          0
Electrical           1
Kitchen Qual         0
Functional           0
Fireplace Qu      1422
Garage Type        157
Garage Finish      159
Garage Qual        159
Garage Cond        159
Paved Drive          0
Pool QC           2917
Fence             2358
Misc Feature      2824
Sale Type            0
Sale Condition       0
dtype: int64

In [32]:
len(ames)

2930

In [33]:
ames.dropna()

Empty DataFrame
Columns: [Order, PID, MS SubClass, MS Zoning, Lot Frontage, Lot Area, Street, Alley, Lot Shape, Land Contour, Utilities, Lot Config, Land Slope, Neighborhood, Condition 1, Condition 2, Bldg Type, House Style, Overall Qual, Overall Cond, Year Built, Year Remod/Add, Roof Style, Roof Matl, Exterior 1st, Exterior 2nd, Mas Vnr Type, Mas Vnr Area, Exter Qual, Exter Cond, Foundation, Bsmt Qual, Bsmt Cond, Bsmt Exposure, BsmtFin Type 1, BsmtFin SF 1, BsmtFin Type 2, BsmtFin SF 2, Bsmt Unf SF, Total Bsmt SF, Heating, Heating QC, Central Air, Electrical, 1st Flr SF, 2nd Flr SF, Low Qual Fin SF, Gr Liv Area, Bsmt Full Bath, Bsmt Half Bath, Full Bath, Half Bath, Bedroom AbvGr, Kitchen AbvGr, Kitchen Qual, TotRms AbvGrd, Functional, Fireplaces, Fireplace Qu, Garage Type, Garage Yr Blt, Garage Finish, Garage Cars, Garage Area, Garage Qual, Garage Cond, Paved Drive, Wood Deck SF, Open Porch SF, Enclosed Porch, 3Ssn Porch, Screen Porch, Pool Area, Pool QC, Fence, Misc Feature, Misc Val, Mo Sold, Yr Sold, Sale Type, Sale Condition, SalePrice]
Index: []

[0 rows x 82 columns]

In [34]:
ames['Misc Feature'].value_counts()

Misc Feature
Shed    95
Gar2     5
Othr     4
Elev     1
TenC     1
Name: count, dtype: int64

In [36]:
ames=ames.drop(columns=['Misc Feature','Fence','Alley'])
ames

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,0,120,0,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,IR1,Low,AllPub,...,0,0,0,NaN,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,11,2006,WD,Normal,188000

In [37]:
ames.dropna()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1063,1064,528164060,20,RL,106.0,12720,Pave,Reg,HLS,AllPub,...,0,216,144,Ex,0,2,2008,WD,Normal,615000
1498,1499,908154235,60,RL,313.0,63887,Pave,IR3,Bnk,AllPub,...,0,0,480,Gd,0,1,2008,New,Partial,160000
2350,2351,527356020,60,RL,80.0,16692,Pave,IR1,Lvl,AllPub,...,0,440,519,Fa,2000,7,2006,WD,Normal,250000
2357,2358,527377030,20,RL,78.0,10140,Pave,Reg,Lvl,AllPub,...,0,0,648,Fa,0,1,2006,WD,Normal,181000
2498,2499,532476050,80,RL,100.0,14330,Pave,IR1,Low,AllPub,...,0,0,800,Gd,0,1,2006,WD,Normal,260000

In [40]:
ames.head(20)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,0,120,0,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.0,9978,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.0,4920,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.0,5005,Pave,IR1,HLS,AllPub,...,0,144,0,NaN,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.0,5389,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.0,7500,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,6,2010,WD,Normal,189000
10,11,527163010,60,RL,75.0,10000,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,4,2010,WD,Normal,175900
11,12,527165230,20,RL,NaN,7980,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,500,3,2010,WD,Normal,185000
12,13,527166040,60,RL,63.0,8402,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,5,2010,WD,Normal,180400
13,14,527180040,20,RL,85.0,10176,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,2,2010,WD,Normal,171500
14,15,527182190,120,RL,NaN,6820,Pave,IR1,Lvl,AllPub,...,0,140,0,NaN,0,6,2010,WD,Normal,212000
15,16,527216070,60,RL,47.0,53504,Pave,IR2,HLS,AllPub,...,0,210,0,NaN,0,6,2010,WD,Normal,538000
16,17,527225035,50,RL,152.0,12134,Pave,IR1,Bnk,AllPub,...,0,0,0,NaN,0,6,2010,WD,Normal,164000
17,18,527258010,20,RL,88.0,11394,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,6,2010,New,Partial,394432
18,19,527276150,20,RL,140.0,19138,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,6,2010,WD,Normal,141000
19,20,527302110,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,2,2010,WD,Normal,210000

In [ ]:
ames['Lot Frontage'].mean()

np.float64(69.22459016393442)

In [42]:
ames['Lot Frontage'].fillna(ames['Lot Frontage'].mean())

0       141.00000
1        80.00000
2        81.00000
3        93.00000
4        74.00000
          ...
2925     37.00000
2926     69.22459
2927     62.00000
2928     77.00000
2929     74.00000
Name: Lot Frontage, Length: 2930, dtype: float64

In [43]:
ames['Lot Frontage']=ames['Lot Frontage'].fillna(ames['Lot Frontage'].mean())

In [44]:
ames.head(3)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,0,120,0,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,12500,6,2010,WD,Normal,172000

In [50]:
ames['Sale Condition']=ames['Sale Condition'].fillna(ames['Sale Condition'].mode()[0])

In [46]:
ames.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,0,120,0,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,0,0,0,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,0,0,0,NaN,0,3,2010,WD,Normal,189900

In [49]:
ames['Sale Condition'].mode()[0]

'Normal'

In [48]:
ames['Lot Frontage'].mean()

np.float64(69.22459016393442)

In [54]:
# missing values
# remove (by rows, by columns)
# replacing
#   with constant fillna(0)
#   with statistical inforamation (mean, mode, max, min)
#   with methods (bfill, ffill, interplote)


ames.select_dtypes(include='number').isnull().sum()

Order                0
PID                  0
MS SubClass          0
Lot Frontage         0
Lot Area             0
Overall Qual         0
Overall Cond         0
Year Built           0
Year Remod/Add       0
Mas Vnr Area        23
BsmtFin SF 1         1
BsmtFin SF 2         1
Bsmt Unf SF          1
Total Bsmt SF        1
1st Flr SF           0
2nd Flr SF           0
Low Qual Fin SF      0
Gr Liv Area          0
Bsmt Full Bath       2
Bsmt Half Bath       2
Full Bath            0
Half Bath            0
Bedroom AbvGr        0
Kitchen AbvGr        0
TotRms AbvGrd        0
Fireplaces           0
Garage Yr Blt      159
Garage Cars          1
Garage Area          1
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Misc Val             0
Mo Sold              0
Yr Sold              0
SalePrice            0
dtype: int64

In [58]:
ames['Mas Vnr Area'].tail(100)

2830     50.0
2831     50.0
2832    117.0
2833      0.0
2834      0.0
        ...
2925      0.0
2926      0.0
2927      0.0
2928      0.0
2929     94.0
Name: Mas Vnr Area, Length: 100, dtype: float64

In [62]:
ames[ames['Mas Vnr Area'].isnull()][['PID','Mas Vnr Area']].head()

           PID  Mas Vnr Area
55   528240070           NaN
484  528275160           NaN
517  528458020           NaN
538  531371050           NaN
867  907260030           NaN

In [66]:
ames.iloc[54,][['PID','Mas Vnr Area']]

PID             528231020
Mas Vnr Area          0.0
Name: 54, dtype: object

In [67]:
ames.iloc[483,][['PID','Mas Vnr Area']]

PID             528275070
Mas Vnr Area          0.0
Name: 483, dtype: object

In [68]:
ames.iloc[485,][['PID','Mas Vnr Area']]

PID             528280230
Mas Vnr Area         40.0
Name: 485, dtype: object

In [70]:
temp_data=ames['Mas Vnr Area'].bfill()
temp_data

0       112.0
1         0.0
2       108.0
3         0.0
4         0.0
        ...
2925      0.0
2926      0.0
2927      0.0
2928      0.0
2929     94.0
Name: Mas Vnr Area, Length: 2930, dtype: float64

In [71]:
temp_data[55]

np.float64(0.0)

In [73]:
temp_data[484]

np.float64(40.0)

In [74]:
temp_data1=ames['Mas Vnr Area'].ffill()
temp_data1[484]

np.float64(0.0)

In [ ]:
temp_data1=ames['Mas Vnr Area'].fillna(methods='interpolate')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'methods'

In [80]:
temp2=ames['Mas Vnr Area'].interpolate()
temp2[484]

np.float64(20.0)